server:
  port: 8081
spring:
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    from:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true